---
title: "Manual de Demografía y Bioestadística"
author: "Fabián Almirall Marchena"
lang: es
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
---

# Parte I: Composición de la Población

## 1. Razón de masculinidad

También es llamada razón de sexo en algunos casos.

Fórmula:

$$
\text{Razón  de  masculidad} = \frac{N_{Masc}}{N_{Fem}} * 100
$$

Interpretación: Cantidad de hombres que hay en una población por cada 100 mujeres.

Por ejemplo, si la razón de masculinidad es igual a 90. Se interpreta como que hay 90 hombres por cada 100 mujeres.

``` r
Razon_M = (pob_masc/pob_fem)*100
```

**Observaciones:**

-   La razón de masculinidad al nacimiento refleja patrones biológicos más o menos estables en distintas poblaciones.

-   En la mayoría de las poblaciones humanas en las que se haya erradicado la mortalidad materna, la curva de razón de masculinidad por edad sigue un patrón descendente claro.

``` r
# Librerías

library(ggplot2)
library(dplyr)

# Limpieza de los datos



# Gráfico
```

(Pendiente código)

## 2. Pirámidez poblacionales

(pendiente)

## 3. Subgrupos Especiales

-   Población a la edad 0: Razón de masculinidad  105

-   Población de 0 a 14 años: Población dependiente joven

-   Población de 15 a 64 años: Población en edades laborales

-   Población de 65 años y más: Población dependiente en edades mayores

## 4. Razones de dependencia

Fórmulas

$$
\text{Razón de dependencia} = \frac{N_{0-14}+N_{+65\text{años}}}{N_{15-64}}*100\\[25pt]
\text{Razón de dependencia joven} = \frac{N_{0-14}}{N_{15-64}}*100\\[25pt]
\text{Razón de dependencia mayor} = \frac{N_{+65\text{años}}}{N_{15-64}}*100\\[25pt]
\text{Razón de envejecimiento} = \frac{N_{+65\text{años}}}{N_{0-14}}*100
$$

Interpretaciones: Para cada interpretación se toma el nombre de la subgrupo de estudio. Por ejemplo:

-   Si la razón de dependencia es igual 91. Entonces, hay 91 personas pertenecientes a la población dependiente joven y mayor, por cada 100 personas pertenecientes a la población en edades laborales.

-   Si la razón de envejecimiento es igual a 82. Entonces, hay 82 personas dependientes en edades mayores por cada 100 personas dependientes en edades jovenes.

### Razón de longevidad

Es un indicador muy utilizado para medir longevidad

$$
\text{Razón de longevidad} = \frac{N_{+75\text{años}}}{N_{+65\text{años}}}
$$

Interpretación:

### Razón Niño /Mujer

Es un indicador muy utilizado para medir fecundidad

Fórmula:

$$
\text{Razón Niño/Mujer} = \frac{N_{0-14}}{NF_{15-49}}*100
$$

Interpretación:

## 5. Calidad de la Información sobre composición por sexo y edad

Cuando se usan censos de población y encuestas para analizar la distribución por edad, la verdadera distribución está afectada por distintos problemas que afectan la calidad del dato:

-   Omisión diferenciada

-   Preferencia de dígitos

-   Exageración de la edad (En Encuestas):

-   Desactualización de marcos muestrales o diseños muestrales con sesgos de selección.

Y existen medidas para analizar la calidad en la declaración de la edad:

-   Índice de Whipple

-   Índice de Myers

## 6. Índice de Whipple

El índice de Whipple se usa para medir la atracción de un dígito final en la declaración de la edad, sobre todo el 5 y el 0. Y este utiliza el supuesto de que los dígitos finales de las edades siguen una distribución uniforme.

Fórumulas:

$$
I_W = \frac{5 * \sum_{i=5}^{12} N_{5i}}{\sum_{i=23}^{62} N_i} * 100\\[35pt]
I_W = \frac{5 * (N_{25} + N_{30} + N_{35} + N_{40} + N_{45} + N_{50} + N_{55} + N_{60})}{N_{23-62}} * 100\\[35pt]
\text{Solo para el dígito 0: } I_W = \frac{10 * (N_{30} + N_{40} + N_{50} + N_{60})}{N_{30-69}} * 100\\[35pt]
\text{Solo para el dígito 5: } I_W = \frac{10 * (N_{25} + N_{35} + N_{45} + N_{55})}{N_{25-64}} * 100
$$

Interpretación:

| Rango de IW | Clasificación de la información |
|-------------|---------------------------------|
| 100 a 104   | Muy precisa                     |
| 105 a 109   | Precisa                         |
| 110 a 124   | Aproximada                      |
| 125 a 174   | Deficiente                      |
| 175 a más   | Muy deficiente                  |

Código en R

``` r
```

## 7. Índice de Myers

El índice de Myers también se usa para analizar preferencia hacia algún dígito y supone también que los los dígitos finales en las edades siguen una distribución uniforme.

Fórmula:

$$
M_j = (j + 1) * v_j + (10 - j) * v'_j\\[35pt]
I_M = 100 * \sum \left| \frac{M_j}{\sum M_j} - 0.1 \right|
$$

Interpretación:

| Rango de IM | Clasificación de la información     |
|-------------|-------------------------------------|
| 0 a 4.99    | Baja concentración de un dígito     |
| 5 a 14.99   | Mediana concentración de un dígito  |
| 15 a 29.99  | Alta concentración de un dígito     |
| 30 a más    | Muy alta concentración de un dígito |

Quarto enables y

``` r




base <- read.csv("~/Académico/2026/Ciclo I/Estadística/Introducción a la Demografía y Bioestadística/Presentaciones y temas/Clase 3/consumo_y_estatura.csv")


summary(base)


# Se calcula el promedio de las calorias

prom.calorias = mean(base$hatcalor, na.rm = T)

# Se hace el modelo de regresión}

mod = lm(base$hatcalor ~ base$tallam, base)

# Se calculan las nuevas calorías 

nuevas.calorias = prom.calorias + mod$res





# Se calcula la prevalencia

prevalencia.bruta  = round(100*(mean(base$hatcalor>=2100, na.rm = T)))

prevalencia.bruta
library(car)

crPlots(mod)
summary(mod$res)
```

El supuesto más importante es el de linealiedad, (che3carlo luego )

## Laboratorio de exposición al riesgo

``` r

library(dplyr)
library(lubridate)

base <- read.csv("~/Académico/2026/Ciclo I/Estadística/Introducción a la Demografía y Bioestadística/Asignaciones/Lab; Exposición al riesgo/muestrapob.csv")

base_def = base %>% 
  filter(murio == 1) %>% 
  summarise(numero_muertes= n()) 

base_def


base_julio2015 <- base %>% 
  filter(anyodefun == 2015 & mesdefun == 7 | is.na(anyodefun)) %>% 
  summarise(tasa_mortalida = (sum(murio == 1)/n())*1000)

# Parte 3



base_final <- base %>%
  mutate(
    # 1. Se crea la fecha de defunción
    fecha_muerte = make_date(year = anyodefun, month = mesdefun, day = diadefun),
    
    # 2. Fecha de referencia
    inicio_anio = ymd("2015-01-01"),
    
    # 3. Cálculo con ifelse
    tiempo_vivido = ifelse(murio == 1, 
                           as.numeric(fecha_muerte - inicio_anio + 1) / 365, 
                           1)
  )
# 4. Cálculo de la Tasa Bruta de Mortalidad (TBM)
total_muertes <- sum(base_final$murio == 1, na.rm = TRUE)
total_anos_persona <- sum(base_final$tiempo_vivido, na.rm = TRUE)

tbm_exacta <- (total_muertes / total_anos_persona) * 1000

print(paste("Años-persona totales:", round(total_anos_persona, 2)))
print(paste("TBM Exacta:", round(tbm_exacta, 2)))



base_analisis <- base %>%
  mutate(tiempo_vivido = ifelse(murio == 1, 0.5, 1))

# Sumamos todos los años-persona
total_anos_persona <- sum(base_analisis$tiempo_vivido)

# Contamos las muertes para el numerador
total_muertes <- sum(base_analisis$murio == 1)

# Tasa Bruta de Mortalidad
tbm_final <- (total_muertes / total_anos_persona) * 1000
```

## Suavizamiento

Hay métodos específicos de suvizamientos

Prorrateo: Es una téctnica que se utiliza para no obviar datos que no son especificados

## Componentes de cambio demográfico

### Modelos de crecimiento

#### Modelo de crecimiento logístico

#### Modelo de crecimiento geométrico+

#### Modelo de crecimiento exponencial

Para calcular los tiempos se utilizan las siguientes fórumulas:

$$
t = (Año_f-Año_0)-\frac{(Mes_f-Mes_0)}{12}-\frac{Día_f-Día_0}{365.25}
$$

$$
t'(1) = (Año_\text{t'(1)}-Año_\text{pivote})-\frac{(Mes_\text{t'(1)}-Mes_\text{pivote})}{12}-\frac{Día_\text{t'(1)}-Día_\text{pivote}}{365.25}
$$

$$
t'(2) = (Año_\text{t'(2)}-Año_\text{pivote})-\frac{(Mes_\text{t'(2)}-Mes_\text{pivote})}{12}-\frac{Día_\text{t'(2)}-Día_\text{pivote}}{365.25}
$$

**Observación:** Para pivotear se pueden tomar cualquier tiempo de población. En teoría no deberían haber diferencias entre los resultados las proyecciones.
